name: learn-github-actions
on:
  pull_request:
    types: [openend,merged,reopened]
jobs:
  build:
    runs-on: [self-hosted,common-8gb]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5.3.0
        with: 
          python-version: '3.12'
      - uses: py-actions/py-dependency-install@v4
      - run: python3 src/train.py     
    
