name: Model-Training-Test
on:
  pull_request:
    types: [opened, reopened, edited, merged]
  push:
    branches:
    - main
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v4
        with:
          repository: 'ChristianSchoener/Software-Engineering_2_Repo'
      - uses: actions/setup-python@v5.3.0
        with:
          python-version: 3.12
      - uses: py-actions/py-dependency-install@v4
      - run: python3 src/train.py
      - uses: actions/upload-artifact@v4.5.0
        with:
          name: auto-mpg-model_artifact
          path: data/model/auto-mpg-baujahr
